INSERT INTO m_standard(std_id,std_name,abbr,category) VALUES (1,'Nursery','N','Preschool');
INSERT INTO m_standard(std_id,std_name,abbr,category) VALUES (2,'Junior KG','JK','Preschool');
INSERT INTO m_standard(std_id,std_name,abbr,category) VALUES (3,'Senior KG','SK','Preschool');
INSERT INTO m_standard(std_id,std_name,abbr,category) VALUES (4,'STD 1','I','Primary School');
INSERT INTO m_standard(std_id,std_name,abbr,category) VALUES (5,'STD 2','II','Primary School');
INSERT INTO m_standard(std_id,std_name,abbr,category) VALUES (6,'STD 3','III','Primary School');
INSERT INTO m_standard(std_id,std_name,abbr,category) VALUES (7,'STD 4','IV','Primary School');
INSERT INTO m_standard(std_id,std_name,abbr,category) VALUES (8,'STD 5','V','Middle School');
INSERT INTO m_standard(std_id,std_name,abbr,category) VALUES (9,'STD 6','VI','Middle School');
INSERT INTO m_standard(std_id,std_name,abbr,category) VALUES (10,'STD 7','VII','Middle School');
INSERT INTO m_standard(std_id,std_name,abbr,category) VALUES (11,'STD 8','VIII','Secondary School');
INSERT INTO m_standard(std_id,std_name,abbr,category) VALUES (12,'STD 9','IX','Secondary School');
INSERT INTO m_standard(std_id,std_name,abbr,category) VALUES (13,'STD 10','X','Secondary School');
INSERT INTO m_standard(std_id,std_name,abbr,category) VALUES (14,'STD 11','XI','High School');
INSERT INTO m_standard(std_id,std_name,abbr,category) VALUES (15,'STD 12','XII','High School');
INSERT INTO m_standard(std_id,std_name,abbr,category) VALUES (16,'UG','UG','Bachelors');
INSERT INTO m_standard(std_id,std_name,abbr,category) VALUES (17,'PG','PG','Masters');
INSERT INTO m_standard(std_id,std_name,abbr,category) VALUES (18,'Professional','Prof','Professional');
INSERT INTO m_standard(std_id,std_name,abbr,category) VALUES (19,'Others','Others','Others');
